// flow-typed signature: 9b53c3317fd7f054fcdff1e1a307b4cc
// flow-typed version: <<STUB>>/@octokit/plugin-throttling_v^2.4.0/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/plugin-throttling'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/plugin-throttling' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/plugin-throttling/lib' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/lib/route-matcher' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/lib/wrap-request' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/scripts/generate-routes' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/test/integration/events' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/test/integration' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/test/integration/octokit' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/test/integration/retry' {
  declare module.exports: any
}

declare module '@octokit/plugin-throttling/test/memory-leakage-test' {
  declare module.exports: any
}

// Filename aliases
declare module '@octokit/plugin-throttling/lib/index' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/lib'>
}
declare module '@octokit/plugin-throttling/lib/index.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/lib'>
}
declare module '@octokit/plugin-throttling/lib/route-matcher.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/lib/route-matcher'>
}
declare module '@octokit/plugin-throttling/lib/wrap-request.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/lib/wrap-request'>
}
declare module '@octokit/plugin-throttling/scripts/generate-routes.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/scripts/generate-routes'>
}
declare module '@octokit/plugin-throttling/test/integration/events.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/integration/events'>
}
declare module '@octokit/plugin-throttling/test/integration/index' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/integration'>
}
declare module '@octokit/plugin-throttling/test/integration/index.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/integration'>
}
declare module '@octokit/plugin-throttling/test/integration/octokit.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/integration/octokit'>
}
declare module '@octokit/plugin-throttling/test/integration/retry.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/integration/retry'>
}
declare module '@octokit/plugin-throttling/test/memory-leakage-test.js' {
  declare module.exports: $Exports<'@octokit/plugin-throttling/test/memory-leakage-test'>
}
