// flow-typed signature: 2faf85a741ff911fc1f7dd940427e464
// flow-typed version: <<STUB>>/@octokit/rest_v^16.25.1/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/rest' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/rest/lib/constructor' {
  declare module.exports: any
}

declare module '@octokit/rest/lib/core' {
  declare module.exports: any
}

declare module '@octokit/rest/lib/factory' {
  declare module.exports: any
}

declare module '@octokit/rest/lib/parse-client-options' {
  declare module.exports: any
}

declare module '@octokit/rest/lib/register-plugin' {
  declare module.exports: any
}

declare module '@octokit/rest/lib/request-with-defaults' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication-deprecated/authenticate' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication-deprecated/before-request' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication-deprecated' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication-deprecated/request-error' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication/before-request' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication/request-error' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication/validate' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/authentication/with-authorization-prefix' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/log' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/normalize-git-reference-responses' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/pagination' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/pagination/iterator' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/pagination/normalize-paginated-list-response' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/pagination/paginate' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/register-endpoints' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/register-endpoints/register-endpoints' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/rest-api-endpoints' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/validate' {
  declare module.exports: any
}

declare module '@octokit/rest/plugins/validate/validate' {
  declare module.exports: any
}

// Filename aliases
declare module '@octokit/rest/index' {
  declare module.exports: $Exports<'@octokit/rest'>
}
declare module '@octokit/rest/index.js' {
  declare module.exports: $Exports<'@octokit/rest'>
}
declare module '@octokit/rest/lib/constructor.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/constructor'>
}
declare module '@octokit/rest/lib/core.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/core'>
}
declare module '@octokit/rest/lib/factory.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/factory'>
}
declare module '@octokit/rest/lib/parse-client-options.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/parse-client-options'>
}
declare module '@octokit/rest/lib/register-plugin.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/register-plugin'>
}
declare module '@octokit/rest/lib/request-with-defaults.js' {
  declare module.exports: $Exports<'@octokit/rest/lib/request-with-defaults'>
}
declare module '@octokit/rest/plugins/authentication-deprecated/authenticate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication-deprecated/authenticate'>
}
declare module '@octokit/rest/plugins/authentication-deprecated/before-request.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication-deprecated/before-request'>
}
declare module '@octokit/rest/plugins/authentication-deprecated/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication-deprecated'>
}
declare module '@octokit/rest/plugins/authentication-deprecated/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication-deprecated'>
}
declare module '@octokit/rest/plugins/authentication-deprecated/request-error.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication-deprecated/request-error'>
}
declare module '@octokit/rest/plugins/authentication/before-request.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/before-request'>
}
declare module '@octokit/rest/plugins/authentication/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication'>
}
declare module '@octokit/rest/plugins/authentication/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication'>
}
declare module '@octokit/rest/plugins/authentication/request-error.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/request-error'>
}
declare module '@octokit/rest/plugins/authentication/validate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/validate'>
}
declare module '@octokit/rest/plugins/authentication/with-authorization-prefix.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/authentication/with-authorization-prefix'>
}
declare module '@octokit/rest/plugins/log/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/log'>
}
declare module '@octokit/rest/plugins/log/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/log'>
}
declare module '@octokit/rest/plugins/normalize-git-reference-responses/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/normalize-git-reference-responses'>
}
declare module '@octokit/rest/plugins/normalize-git-reference-responses/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/normalize-git-reference-responses'>
}
declare module '@octokit/rest/plugins/pagination/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination'>
}
declare module '@octokit/rest/plugins/pagination/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination'>
}
declare module '@octokit/rest/plugins/pagination/iterator.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/iterator'>
}
declare module '@octokit/rest/plugins/pagination/normalize-paginated-list-response.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/normalize-paginated-list-response'>
}
declare module '@octokit/rest/plugins/pagination/paginate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/pagination/paginate'>
}
declare module '@octokit/rest/plugins/register-endpoints/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/register-endpoints'>
}
declare module '@octokit/rest/plugins/register-endpoints/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/register-endpoints'>
}
declare module '@octokit/rest/plugins/register-endpoints/register-endpoints.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/register-endpoints/register-endpoints'>
}
declare module '@octokit/rest/plugins/rest-api-endpoints/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/rest-api-endpoints'>
}
declare module '@octokit/rest/plugins/rest-api-endpoints/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/rest-api-endpoints'>
}
declare module '@octokit/rest/plugins/validate/index' {
  declare module.exports: $Exports<'@octokit/rest/plugins/validate'>
}
declare module '@octokit/rest/plugins/validate/index.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/validate'>
}
declare module '@octokit/rest/plugins/validate/validate.js' {
  declare module.exports: $Exports<'@octokit/rest/plugins/validate/validate'>
}
