// flow-typed signature: c43d87ba2eba5aaf5be063ea66bcef00
// flow-typed version: <<STUB>>/npm-registry-fetch_v^3.9.0/flow_v0.143.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-registry-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-registry-fetch' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-registry-fetch/auth' {
  declare module.exports: any
}

declare module 'npm-registry-fetch/check-response' {
  declare module.exports: any
}

declare module 'npm-registry-fetch/config' {
  declare module.exports: any
}

declare module 'npm-registry-fetch/errors' {
  declare module.exports: any
}

declare module 'npm-registry-fetch/silentlog' {
  declare module.exports: any
}

// Filename aliases
declare module 'npm-registry-fetch/auth.js' {
  declare module.exports: $Exports<'npm-registry-fetch/auth'>
}
declare module 'npm-registry-fetch/check-response.js' {
  declare module.exports: $Exports<'npm-registry-fetch/check-response'>
}
declare module 'npm-registry-fetch/config.js' {
  declare module.exports: $Exports<'npm-registry-fetch/config'>
}
declare module 'npm-registry-fetch/errors.js' {
  declare module.exports: $Exports<'npm-registry-fetch/errors'>
}
declare module 'npm-registry-fetch/index' {
  declare module.exports: $Exports<'npm-registry-fetch'>
}
declare module 'npm-registry-fetch/index.js' {
  declare module.exports: $Exports<'npm-registry-fetch'>
}
declare module 'npm-registry-fetch/silentlog.js' {
  declare module.exports: $Exports<'npm-registry-fetch/silentlog'>
}
